"""
Ansible Playbook 실행기

실행 모드:
  - local: subprocess로 직접 실행 (kind/dev 환경)
  - ssh:   master#1에 SSH 접속하여 실행 (production, 미구현 → TODO)

상태 매핑 (ansible JSON callback 출력 기반):
  - 모든 호스트 failures=0, unreachable=0  → healthy (초록)
  - 어느 호스트든 failures > 0             → critical (빨강)
  - 그 외 (unreachable, changed 등)         → warning (주황)

Inventory 우선순위:
  1) ``inventory_content`` (DB 에 저장된 Ansible Inventory 본문 → 임시 파일)
  2) ``inventory_path``    (사용자가 명시적으로 지정한 파일 경로)
  3) ``inventory_hosts``   (K8s API 등에서 가져온 노드 리스트 — 임시 파일 자동 생성)
  4) 정적 fallback ``{ansible_inventory_dir}/clusters.yml``

Playbook 본문도 동일하게 ``playbook_content`` 가 주어지면 임시 파일로 머터리얼라이즈.
"""
import contextlib
import json
import os
import re
import subprocess
import tempfile
from datetime import datetime
from typing import Any

from app.config import settings


class PlaybookResult:
    def __init__(
        self,
        status: str,
        message: str,
        duration_ms: int = 0,
        stats: dict[str, Any] | None = None,
        raw_output: str = "",
    ):
        self.status = status
        self.message = message
        self.duration_ms = duration_ms
        self.stats = stats or {}
        self.raw_output = raw_output


def _truncate(text: str, limit: int = 5000) -> str:
    if len(text) <= limit:
        return text
    return f"{text[:limit]}\n...<truncated {len(text) - limit} chars>"


def _build_raw_output(stdout: str, stderr: str) -> str:
    """stdout/stderr를 함께 저장해 장애 분석 시 단서를 잃지 않도록 한다."""
    chunks: list[str] = []
    if stdout:
        chunks.append("=== STDOUT ===")
        chunks.append(stdout)
    if stderr:
        chunks.append("=== STDERR ===")
        chunks.append(stderr)
    return _truncate("\n".join(chunks), limit=10000)


@contextlib.contextmanager
def _materialized(content: str | None, suffix: str):
    """주어진 content 를 임시 파일로 쓰고 경로를 yield. None 이면 None yield."""
    if content is None:
        yield None
        return
    fd, path = tempfile.mkstemp(suffix=suffix, prefix="ansible-")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        yield path
    finally:
        try:
            os.unlink(path)
        except OSError:
            pass


def _build_dynamic_inventory(hosts: list[str]) -> str:
    """동적 inventory 문자열을 만든다 (`[all]` 그룹 + host_key_checking off).

    호스트 변수(ansible_user / ansible_ssh_pass / ansible_ssh_private_key_file 등)는
    playbook.extra_vars 로 `-e` 전달돼 group_vars 처럼 적용된다.
    호스트키 검사는 사내망 전제로 비활성 — Settings 로 노출하고 싶으면 추후 분리.
    """
    # shell injection / 잘못된 토큰 차단 — IPv4 / IPv6 / FQDN 만 허용
    safe = [h for h in (hosts or []) if h and re.match(r"^[A-Za-z0-9_.:\-\[\]]+$", h)]
    lines = [
        "# auto-generated by k8s_daily_monitor — cluster nodes from K8s API",
        "[all]",
        *safe,
        "",
        "[all:vars]",
        "ansible_host_key_checking=False",
        "ansible_ssh_common_args='-o StrictHostKeyChecking=no'",
        "",
    ]
    return "\n".join(lines)


def run_playbook(
    playbook_path: str | None = None,
    inventory_path: str | None = None,
    extra_vars: dict[str, Any] | None = None,
    tags: str | None = None,
    timeout: int | None = None,
    *,
    playbook_content: str | None = None,
    inventory_content: str | None = None,
    inventory_hosts: list[str] | None = None,
    ssh_private_key: str | None = None,
) -> PlaybookResult:
    """ansible-playbook을 JSON callback과 함께 실행하고 결과를 파싱합니다.

    inventory 우선순위:
      1) ``inventory_content`` — DB 관리형 Inventory 본문 (임시 파일 materialize)
      2) ``inventory_path``    — 사용자가 명시한 파일 경로
      3) ``inventory_hosts``   — K8s API 로 가져온 노드 리스트 (동적 생성)
      4) ``{ansible_inventory_dir}/clusters.yml`` 정적 fallback
    """

    if not (playbook_path or playbook_content):
        return PlaybookResult(
            status="critical",
            message="playbook_path 또는 playbook_content 중 하나는 필수입니다.",
            duration_ms=0,
        )

    # inventory_hosts 만 주어지면 동적 inventory 본문을 생성하고 그 후 _materialized 로 처리.
    # inventory_content 가 이미 있으면 그것이 우선이고, inventory_hosts 는 무시됨.
    effective_inv_content = inventory_content
    if effective_inv_content is None and not inventory_path and inventory_hosts:
        effective_inv_content = _build_dynamic_inventory(inventory_hosts)

    env = {
        "ANSIBLE_STDOUT_CALLBACK": "json",
        "ANSIBLE_LOAD_CALLBACK_PLUGINS": "1",
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "HOME": "/root",
    }
    effective_timeout = timeout or settings.check_timeout_seconds
    start = datetime.utcnow()

    with _materialized(playbook_content, ".yml") as pb_temp, \
         _materialized(effective_inv_content, ".ini") as inv_temp, \
         _materialized(ssh_private_key, ".pem") as key_temp:
        effective_pb = pb_temp or playbook_path
        effective_inv = inv_temp or inventory_path

        # 임시 키 파일은 0600 으로 권한 강제 — ansible/SSH 가 거부하지 않도록.
        if key_temp:
            try:
                os.chmod(key_temp, 0o600)
            except OSError:
                pass

        cmd = ["ansible-playbook", str(effective_pb)]
        if effective_inv:
            cmd.extend(["-i", str(effective_inv)])
        else:
            default_inv = f"{settings.ansible_inventory_dir}/clusters.yml"
            cmd.extend(["-i", default_inv])

        # 인라인 자격증명을 -e 로 머지 — 키 경로는 임시 파일이라 extra_vars 와 합친 뒤 전달.
        merged_vars: dict[str, Any] = dict(extra_vars or {})
        if key_temp:
            merged_vars["ansible_ssh_private_key_file"] = key_temp
        if merged_vars:
            cmd.extend(["-e", json.dumps(merged_vars)])
        if tags:
            cmd.extend(["--tags", tags])

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=effective_timeout,
                env=env,
            )
            elapsed = int((datetime.utcnow() - start).total_seconds() * 1000)
            return _parse_result(result, elapsed)

        except subprocess.TimeoutExpired:
            elapsed = int((datetime.utcnow() - start).total_seconds() * 1000)
            return PlaybookResult(
                status="critical",
                message=f"Playbook timed out after {effective_timeout}s",
                duration_ms=elapsed,
            )
        except FileNotFoundError:
            return PlaybookResult(
                status="critical",
                message="ansible-playbook command not found. Install ansible in the execution environment.",
                duration_ms=0,
            )
        except Exception as e:
            elapsed = int((datetime.utcnow() - start).total_seconds() * 1000)
            return PlaybookResult(
                status="critical",
                message=f"Execution error: {str(e)}",
                duration_ms=elapsed,
            )


def _parse_result(result: subprocess.CompletedProcess, elapsed: int) -> PlaybookResult:
    """ansible JSON callback 출력을 파싱하여 상태를 결정합니다."""
    raw = result.stdout or ""
    stderr = result.stderr or ""
    combined_output = _build_raw_output(raw, stderr)

    # JSON 파싱 시도
    try:
        data = json.loads(raw)
    except (json.JSONDecodeError, ValueError):
        # JSON이 아닌 경우 returncode 기반 판단
        if result.returncode == 0:
            return PlaybookResult(
                status="healthy",
                message="Playbook completed successfully (non-JSON output)",
                duration_ms=elapsed,
                raw_output=combined_output,
            )
        return PlaybookResult(
            status="critical",
            message=f"Playbook failed (rc={result.returncode}): {stderr[:500]}",
            duration_ms=elapsed,
            raw_output=combined_output,
        )

    # stats 파싱
    stats = data.get("stats", {})
    if not stats:
        # stats가 없으면 returncode 기반
        status = "healthy" if result.returncode == 0 else "critical"
        return PlaybookResult(
            status=status,
            message="Playbook completed" if status == "healthy" else "Playbook failed",
            duration_ms=elapsed,
            stats=stats,
            raw_output=combined_output,
        )

    # 호스트별 통계 집계
    total_ok = 0
    total_changed = 0
    total_failures = 0
    total_unreachable = 0
    total_skipped = 0
    host_details = {}

    for host, host_stats in stats.items():
        ok = host_stats.get("ok", 0)
        changed = host_stats.get("changed", 0)
        failures = host_stats.get("failures", 0)
        unreachable = host_stats.get("unreachable", 0)
        skipped = host_stats.get("skipped", 0)

        total_ok += ok
        total_changed += changed
        total_failures += failures
        total_unreachable += unreachable
        total_skipped += skipped

        host_details[host] = {
            "ok": ok,
            "changed": changed,
            "failures": failures,
            "unreachable": unreachable,
            "skipped": skipped,
        }

    # 실패/도달불가 태스크 요약 (JSON callback 이벤트 기반)
    failed_tasks = []
    unreachable_tasks = []
    for play in data.get("plays", []):
        play_name = play.get("play", {}).get("name") or "unnamed-play"
        for task in play.get("tasks", []):
            task_name = task.get("task", {}).get("name") or "unnamed-task"
            for host, host_result in (task.get("hosts") or {}).items():
                if host_result.get("failed") is True:
                    failed_tasks.append({
                        "play": play_name,
                        "task": task_name,
                        "host": host,
                        "msg": host_result.get("msg") or host_result.get("stderr") or "task failed",
                    })
                if host_result.get("unreachable") is True:
                    unreachable_tasks.append({
                        "play": play_name,
                        "task": task_name,
                        "host": host,
                        "msg": host_result.get("msg") or "host unreachable",
                    })

    # 상태 결정
    if total_failures > 0:
        status = "critical"
        first = failed_tasks[0] if failed_tasks else None
        tail = f" First failure: [{first['host']}] {first['task']} ({first['play']}) - {first['msg'][:140]}" if first else ""
        message = f"Failed: {total_failures} task(s) failed across {len(stats)} host(s).{tail}"
    elif total_unreachable > 0:
        status = "warning"
        first = unreachable_tasks[0] if unreachable_tasks else None
        tail = f" First unreachable: [{first['host']}] {first['task']} ({first['play']}) - {first['msg'][:140]}" if first else ""
        message = f"Warning: {total_unreachable} host(s) unreachable.{tail}"
    elif total_changed > 0:
        status = "warning"
        message = f"Changed: {total_changed} task(s) changed across {len(stats)} host(s)"
    else:
        status = "healthy"
        message = f"OK: All {total_ok} task(s) passed across {len(stats)} host(s)"

    summary_stats = {
        "hosts": host_details,
        "totals": {
            "ok": total_ok,
            "changed": total_changed,
            "failures": total_failures,
            "unreachable": total_unreachable,
            "skipped": total_skipped,
            "host_count": len(stats),
        },
        "returncode": result.returncode,
        "failed_tasks": failed_tasks[:20],
        "unreachable_tasks": unreachable_tasks[:20],
    }

    return PlaybookResult(
        status=status,
        message=message,
        duration_ms=elapsed,
        stats=summary_stats,
        raw_output=combined_output,
    )
